trigger:
  branches:
    include:
      - '*'
pr: none

pool:
  vmImage: ubuntu-latest 

resources:
  repositories:
    - repository: templates
      type: github
      name: leoviana00/azure-templates-pipeline
      ref: 'refs/heads/azuredevops/templates'
      endpoint: 'leoviana00'

variables:
  - group: acr
  - template: templates/dotnet/ci-vars-template.yml@templates
    parameters:
      projectName: dotnet-pipeline-azure-devops
      dockerRegistryServiceConnectionName: acr-connection-aks
      dockerfile: 'Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'

steps:
  - template: templates/dotnet/ci-steps-template.yml@templates
  
 