resources:
  repositories:
    # Adicionando repositório de templates base para o processo de cicd
    - repository: templates
      type: github
      name: leoviana00/azure-templates-pipeline
      ref: 'refs/heads/main'
      endpoint: 'leoviana00'

    # Adicionando repositório de templates base para helm charts
    - repository: helmrepo
      type: github
      name: leoviana00/azure-template-helm-chart
      ref: 'refs/heads/master'
      endpoint: 'leoviana00'

trigger:
  batch: true
  branches:
    include:
      - '*'

pr: 
- master
- staging

pool:
  vmImage: ubuntu-latest 

variables:
  - group: acr-variable-group
  - template: templates/multistage/dotnet/cicd-vars-pipeline.yml@templates
    parameters:
        projectName: dotnet-pipeline-azure-devops
        dockerRegistryServiceConnectionName: acr-connection-aks
        dockerfile: '$(projectName)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        chartHelmFile: 'azure-template-helm-chart/templates/dotnet/$(projectName)'
  - name: k8sNamespace
    value: gmservice-multistage

stages:
- stage: Prebuild
  displayName: 'Load Template'
  
  jobs: 
  - job: 'Loadtemplate'
    steps:
    - script: echo Load templates
- template: templates/multistage/dotnet/ci-stages-pipeline.yml@templates

# - stage: Deploy
#   displayName: deploy to dev
#   jobs:
#   - deployment: dev
#     variables:
#     - group: aks-variable-group
#     displayName: deploy helm chart into AKS
#     environment: development-$(projectName)
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - template: templates/multistage/dotnet/cd-stages-template.yml@templates

