trigger:
  branches:
    include:
      - '*'
pr: none

pool:
  vmImage: ubuntu-latest 

resources:
  repositories:
    # Adicionando repositório de templates base para o processo de cicd
    - repository: templates
      type: github
      name: leoviana00/azure-templates-pipeline
      ref: 'refs/heads/main'
      endpoint: 'leoviana00'

    # Adicionando repositório de templates base para helm charts
    - repository: helmrepo
      type: github
      name: leoviana00/azure-template-helm-chart
      ref: 'refs/heads/master'
      endpoint: 'leoviana00'

variables:
  - group: acr-variable-group
extends:
  template: templates/cicd-vars-pipeline.yml@templates
  parameters:
    projectName: dotnet-pipeline-azure-devops
    dockerRegistryServiceConnectionName: acr-connection-aks
    dockerfile: '$(projectName)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    chartHelmFile: 'azure-template-helm-chart/templates/dotnet/$(projectName)'

jobs: 
  - checkout: self
  - checkout: helmrepo 
  - template: templates/cicd-stages-pipeline.yml@templates
  
 