resources:
  repositories:
    # Adicionando repositório de templates base para o processo de cicd
    - repository: templates
      type: github
      name: leoviana00/azure-templates-pipeline
      ref: 'refs/heads/main'
      endpoint: 'leoviana00'

    # Adicionando repositório de templates base para helm charts
    - repository: helmrepo
      type: github
      name: leoviana00/azure-template-helm-chart
      ref: 'refs/heads/master'
      endpoint: 'leoviana00'

trigger:
- none

stages:
- stage: Prebuild
  displayName: 'Prebuild'

  variables:
  - group: acr-variable-group
  # - template: templates/cicd-vars-pipeline.yml@templates
    parameters:
          projectName: dotnet-pipeline-azure-devops
          dockerRegistryServiceConnectionName: acr-connection-aks
          dockerfile: '$(projectName)/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          chartHelmFile: 'azure-template-helm-chart/templates/dotnet/$(projectName)'
  
  jobs: 
  - job: 'Prebuild'
    pool:
      vmImage: ubuntu-latest 
    steps:
    - checkout: self
    - checkout: helmrepo 
    # - template: templates/cicd-stages-pipeline.yml@templates

- stage: Build
  displayName: 'Build'
  jobs:
  - job: 'Build'
    pool:
      vmImage: ubuntu-latest 
    steps:
    - script: echo Fake build code

- stage: Deploy
  displayName: 'Deploy'
  jobs:
  - job: 'Deploy'
    pool:
      vmImage: ubuntu-latest 
    steps:
    - script: echo Fake deploy code

 