replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 80
  externalPort: 80
ingress:
  enabled: true
  basedomain: aks-dev-c97889d2.hcp.brazilsouth.azmk8s.io # replace with your own from the portal
